baseURL = 'https://CHANGETHIS.org/'
languageCode = 'en-us'
title = 'EpiSimu 2024'
theme = 'relearn'
[params]
  themeVariant = [  "relearn-light", "relearn-dark", ]
#   themeVariant = [ "auto", "red" ]
